name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Compile
        run: forge build

      - name: Run tests
        run: forge test --fork-url https://eth-mainnet.g.alchemy.com/v2/QJdF0MmlcYioIOEoAnqAU
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Check formatting
        run: forge fmt --check